### PR TITLE
Fixed download again

### PR DESCRIPTION
**Pull request by AlanTheBlank**
Added a user-agent string to the headers, tested and working in Firefox Developer v89.0b7 and Google Chrome 90.0.4430.93

### CODE REVIEW

**Comment by AlanTheBlank** [comment]
noticed I never explained `navigator.userAgent`.  It just gets the user agent of the user and uses it for the request

**Comment by AlanTheBlank** [comment]
Further changes appear to have been made since opening the pull request which has made the fix not work anymore

**Comment by AlanTheBlank** [comment]
I don't know why that initial fix worked.  That wasn't the issue at all, the issue was it couldn't download from fbcdn.net

**Comment by ashokaramani** [comment]
Great product however it suddenly stopped working today. How do I fix this. Can you walk me thru this I am new to it

**Comment by HuiiBuh** [comment]
Thanks for the pr. 
I will update today

**Pull request merged**
