### PR TITLE
Fix InstaID precision without using bigint

### PR DESCRIPTION
**Pull request by Azureit**
With this patch you return the real InstaID, if needed to be checked or used for something else. The one returned now is not precise.

### CODE REVIEW

**Comment by Azureit** [comment]
@HuiiBuh What do you think?
It's good for me, but please optimize and format to meet your standards.

**Comment by HuiiBuh** [comment]
First of all, thanks for the PR.

Honestly, I think you have to put in some comments to explain what exactly you are doing. I half a year I am sure that I will have no clue what this does anymore. 

And if you want to edit a PR, just make some edits in the file (comments), commit the changes and push. This will automatically update the PR for you. 
And some general advice. 
+ In js|ts we use camelCase not snake_case.
+ Don't use magic numbers and don't document them (for a bad example just see my own code which just uses the number 1314220021721 without explaining, that this is the instagram epoch)

**Comment by Azureit** [comment]
@HuiiBuh What do you think now?
Thanks for the tip about editing the branch would update the pr.

**Comment by HuiiBuh** [comment]
Thanks for the edit and the pr.
I will merge it later and release a new version

**Pull request merged**
