### PR TITLE
Fix post download issues

### LINKED ISSUE #233: Download button not working except in stories
# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/world_record_egg/'
2. Click to download
3. Nothing happens, no pop upm window to ask where to download or anything of the sort

**Expected behaviour**
Supposed to allow you to download from instagram but ATM it does nothing

**Screenshots**
No point in adding a screen of the mouse over the download button as there is no error message

**Device (please complete the following information):**
- Resolution: [e.g 2K] 1080p
- Browser [e.g. chrome, firefox] Chrome
- Extension Version 4.5.2

**Additional context**
Funnily enough I tested by adding a story and clicking the download button while in the story and it does download that image, but it is the only download button that works

### PR DESCRIPTION
**Pull request by officialakhil**
**Overview** 

- Fixes #233 

Instagram has updated the response at `?__a=1` for public posts. Private posts still return a graphql response. It looks like the old response is still valid when not logged in. I have kept the logic to handle both kinds of responses based on the `graphql` key existence. 

Let me know of any questions :)

### CODE REVIEW

**Comment by iraouf** [comment]
Hey, I just downloaded the fixed version but when i try to load the zip in chrome it gives me an error "Can't load extension, Manifest file is missing or unreadable, can't load manifest
Schermafbeelding 2021-11-03 om 20 43 33
"

**Comment by officialakhil** [comment]
@iraouf you've to load the `chrome` folder instead of the zip when you're installing with the "Load Unpacked" option.

**Comment by HuiiBuh** [comment]
Thanks a lot @officialakhil 
I will merge the PR. 

Just some general feedback. If you are unsure what kind of object you receive you can use [typeguards](https://www.typescriptlang.org/docs/handbook/advanced-types.html) which will automatically cast objects and make the code more readable.

**Comment by officialakhil** [comment]
Thanks for merging and feedback :)

**Pull request merged**
