### PR TITLE
Fixes for missing download buttons

### PR DESCRIPTION
**Pull request by kmbarr**

### CODE REVIEW

**Comment by kmbarr** [comment]
@HuiiBuh I updated a number of QuerySelectors, to restore the missing download buttons. There is still an issue with some videos that are now coming as blob links from Instagram.

**Comment by kmbarr** [comment]
Spotted at least one more I missed...coming soon.

**Comment by Eikreis** [comment]
Would love to see these be implemented. Meanwhile will attempt to figure out how to install this to Chrome manually--

**Comment by HuiiBuh** [comment]
Hi there thanks a lot :)
I will merge and update.

**Pull request merged**
